# This is a basic workflow to help you get started with Actions

name: Project CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/SpaceDatabase
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use MongoDb
        uses: supercharge/mongodb-github-action@1.6.0
      - name: set Node.js version 16
        uses: actions/setup-node@v3
        with:
          # node-version: '16'
          node-version: ${{ matrix.node-version }}
          mongodb-version: ${{ matrix.mongodb-version }}
      # Runs a single command using the runners shell
      - run: npm install
      # - run: npm run build --prefix client